#!/usr/bin/env node
/**
 * Gets current year via Claude CLI and writes to lib/year.ts
 * Usage: node scripts/get-year.js
 */
const { execSync } = require('child_process')
const fs = require('fs')
const path = require('path')

let year

try {
  const result = execSync(
    'claude --print "Reply with ONLY the current 4-digit year, nothing else. No punctuation, no explanation." 2>/dev/null',
    { encoding: 'utf8', timeout: 15000 }
  ).trim()
  const match = result.match(/\d{4}/)
  if (match) {
    year = parseInt(match[0])
  }
} catch (e) {
  // fallback to system date if Claude CLI unavailable
}

if (!year || year < 2020 || year > 2099) {
  year = new Date().getFullYear()
}

const outPath = path.join(__dirname, '..', 'lib', 'year.ts')
fs.writeFileSync(outPath, `// Auto-generated by scripts/get-year.js via Claude CLI\nexport const SITE_YEAR = ${year}\n`)
console.log(`Year set to ${year}`)
